### ISSUE TITLE
'Unknown encoding: null' due to passing wrong argument to Buffer#toString()

### ISSUE THREAD

**Issue by fatso83** [rse/stmux#23]
I just searched for a tmux replacement using NPM today and found this. Seems perfect. The only issue is that it crashed on first try! And it did this on all Node versions and on both macOS (ARM) and Linux (x86).

If you start up stmux without any arguments and press any key it will crash:
```
$ npx stmux

Unknown encoding: null
```

Just wanted to register the issue before filing a fix. I have verified this issue with Node 12, 14 and 16, so I am not sure why no one has reported, as the code is untouched since 2017 and it can't ever have worked. The above error is for Node 12 and 14, Node 16 is more explicit: 
```
node:buffer:809
    throw new ERR_UNKNOWN_ENCODING(encoding);
    ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: null
    at new NodeError (node:internal/errors:371:5)
    at Buffer.toString (node:buffer:809:11)
    at STMUX.parseOptions (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux-1-options.js:153:28)
    at STMUX.main (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux.js:54:10)
    at Object.<anonymous> (/Users/carlerik/.npm/_npx/feb1cc2f2f2b52b3/node_modules/stmux/bin/stmux.js:77:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'ERR_UNKNOWN_ENCODING'
}
```

**Comment by rse** [comment]
This issue related to encoding is now fixed. Thanks.
